import React from 'react';
import { Container, Image, } from 'react-bootstrap';

function DiscoverArea() {
    return ( 
        <section className="discover_area">
            <div className="container">
                <div className="discover_title">
                    <h2>Finding the right colors can be difficult. So we got your back. Our dedicated team has worked hard to engineer a few methods to assist you with always selecting the right colors for your art .</h2>
                </div>
                <div className="discover_row row">
                    <div className="col-lg-4 col-md-4 col-sm-12 col-12">
                        <div className="discover_col">
                            <p>Random Colors : </p>
                            <p>Our Random Colors feild was create for those who want to start with inspiration and build off of that . Once random colors are generated by our system, one may make changes by changing one, two or all colors Artusine has selected.</p>
                        </div>
                    </div>
                    <div className="col-lg-4 col-md-4 col-sm-12 col-12">
                        <div className="discover_col">
                            <p>Suggested Colors:</p>
                            <p>The design team at Artusine has currated a colloection of color schemes they belive would look great with specific pieces. Feel free to give them a try. We are confidant you will every single color scheme. </p>
                        </div>
                    </div>
                    <div className="col-lg-4 col-md-4 col-sm-12 col-12">
                        <div className="discover_col">
                            <p>Color Harmony:</p>
                            <p>In color theory, color harmony refers to the property that certain aesthetically pleasing color combinations have. These combinations create pleasing contrasts and consonances that are said to be harmonious.</p>
                        </div>
                    </div>
                </div>
                <div className="discover_btn">
                    <a href="#" className="blackBtn">discover now</a>
                </div>
            </div>
        </section>
     );
}

export default DiscoverArea;